"""populate database

Revision ID: 682cab91c784
Revises: a3d292a77fda
Create Date: 2022-04-18 23:01:58.863116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682cab91c784'
down_revision = 'a3d292a77fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_unique_constraint(None, 'tasks_categories', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_categories', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    # ### end Alembic commands ###
