"""update model category

Revision ID: b21834282351
Revises: a7c76583aa4d
Create Date: 2022-04-15 18:47:51.505347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21834282351'
down_revision = 'a7c76583aa4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_unique_constraint(None, 'tasks_categories', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_categories', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    # ### end Alembic commands ###
